#!/bin/sh
INTERACTIVE='true'

# Apps
super + d
	dmenu_run

super + shift + Return
	"$TERMINAL"
	
super + shift + Escape
	"$TERMINAL"

super + p
	"$TERMINAL" -e htop

super + i
	"$TERMINAL" -e "$IRC_CLIENT"
	
super + m
	"$TERMINAL" -e "$MUSIC_PLAYER"
	
super + a
	"$TERMINAL" -e pulsemixer

# Web
super + w; super + { w, s, g, b, r, c }
	web { , Search, Search Google, Bookmarks, Raw, Clipboard }

# sxhkd won't listen for 
# super + e; super + j
# because super + j is taken by
# dwm...
# email + check, work, personal
super + e; super + { e, w, p, s }
	email { -O "$DEFAULT_MAILBOX",  -O lambda, -O jer, -S }

# Bluetooth
super + b; super + { b, t, c, d, s }
	bluetooth { toggle, toggle, connect, disconnect, status } "$BLUETOOTH_DEVICE"

XF86AudioPlay
	mpc toggle

XF86AudioStop
	mpc pause

XF86AudioNext
	mpc next

XF86AudioPrev
	mpc prev

# Utils
super + f
	funnel

Print
	maim -s -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | xclip -selection c -t image/png

Print + shift
	maim -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | xclip -selection c -t image/png

Print + control
	maim -s -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | pasta png

Print + control + shift
	maim -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | pasta png

super + v
	mpv /dev/video0

super + shift + w
	xwininfo | grep 'Window id' | grep -Eo '0x[0-9a-fA-F]+' | xclip -selection c
	
super + grave
	emoji | xclip -selection c

super + F4
	theme reset

super + 0
	echo viewall > "$DWM_CMD_FIFO"

super + {1-9}
	echo view {0-8} > "$DWM_CMD_FIFO"

super + shift + 0
	echo tagall > "$DWM_CMD_FIFO"

super + shift + {1-9}
	echo tag {0-8} > "$DWM_CMD_FIFO"

super + control + {1-9}
	echo toggleview {0-8} > "$DWM_CMD_FIFO"

super + control + shift + {1-9}
	echo toggletag {0-8} > "$DWM_CMD_FIFO"

super + {comma,period}
	echo focusmon {-,+}1 > "$DWM_CMD_FIFO"

super + {h,l}
	echo setmfact {-,+}0.05 > "$DWM_CMD_FIFO"

super + {j,k}
	echo focusstack {-,+}1 > "$DWM_CMD_FIFO"

super + shift + {d,i}
	echo incnmaster {-,+}1 > "$DWM_CMD_FIFO"

super + shift + c
	echo killclient > "$DWM_CMD_FIFO"

super + shift + b
	echo togglebar > "$DWM_CMD_FIFO"

super + shift + q
	echo quit > "$DWM_CMD_FIFO"

super + Tab
	echo toggletagset > "$DWM_CMD_FIFO"

super + Return
	echo zoom > "$DWM_CMD_FIFO"
