#!/bin/sh

# Apps
super + d
	dmenu_run_color

super + shift + Return
	$TERMINAL

super + p
	$TERMINAL -e htop

super + e
	$TERMINAL -e $EMAIL_CLIENT
	

super + i
	notify-send "No more Discord rip"

super + w
	browser_prompt

super + s
	browser_prompt Search Google

# Bluetooth
super + b
	bluetooth connect $BLUETOOTH_DEVICE

super + control + b
	bluetooth status $BLUETOOTH_DEVICE

# Audio
super + m
	$TERMINAL -e ncmpcpp

super + a
	$TERMINAL -e pulsemixer

XF86AudioPlay
	mpc toggle

XF86AudioStop
	mpc pause

XF86AudioNext
	mpc next

XF86AudioPrev
	mpc prev

# Utils
Print
	maim -s -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | xclip -selection c -t image/png

Print + shift
	maim -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | xclip -selection c -t image/png

Print + control
	maim -s -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | pasta png

Print + control + shift
	maim -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | pasta png


super + v
	mpv /dev/video0

super + shift + w
	xwininfo | grep 'Window id' | grep -Eo '0x[0-9a-fA-F]+' | xclip -selection c
	
super + grave
	emoji | xclip -selection c

super + F4
	reset_theme


