#!/bin/sh

# Apps
super + shift + Return
	$TERMINAL

super + m
	$TERMINAL -e ncmpcpp

super + a
	$TERMINAL -e pulsemixer

super + p
	$TERMINAL -e htop


super + i
	discord

super + w
	$BROWSER $HOME_PAGE

super + s
	search

# Bluetooth
super + shift + b
	bluetooth_connect $BLUETOOTH_DEVICE

super + control + b
	bluetooth_status $BLUETOOTH_DEVICE

# Media
XF86AudioPlay
	mpc toggle

XF86AudioStop
	mpc pause

XF86AudioNext
	mpc next

XF86AudioPrev
	mpc prev

# Utils
Print
	maim -s -o | xclip -selection c -t image/png

super + e
	emoji | xclip -selection c
