#!/usr/bin/sh
INTERACTIVE='true'

# Apps
super + d
	dmenu_run

super + shift + Return
	"$TERMINAL"
	
super + shift + Escape
	"$TERMINAL"

super + p
	"$TERMINAL" -e htop

super + i
	"$TERMINAL" -e "$IRC_CLIENT"
	
super + m
	"$TERMINAL" -e "$MUSIC_PLAYER"
	
super + a
	"$TERMINAL" -e pulsemixer

# Web
super + w; super + { w, s, g, b, u, c }
	web { , Search, Search Google, Bookmarks, URL, Clipboard }

# sxhkd won't listen for 
# super + e; super + j
# because super + j is taken by
# dwm...
# email + check, work, personal
super + e; super + { e, w, p, s }
	email { -O "$DEFAULT_MAILBOX",  -O lambda, -O jer, -S }

# Bluetooth
super + b; super + { b, t, c, d, s }
	bluetooth { toggle, toggle, connect, disconnect, status } "$BLUETOOTH_DEVICE"

XF86AudioPlay
	mpc toggle

XF86AudioStop
	mpc pause

XF86AudioNext
	mpc next

XF86AudioPrev
	mpc prev

# Utils
Print
	maim -s -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | xclip -selection c -t image/png

Print + shift
	maim -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | xclip -selection c -t image/png

Print + control
	maim -s -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | pasta png

Print + control + shift
	maim -o | tee "$HOME/Media/Images/Screenshots/$(date +%s).png" | pasta png

super + v
	mpv /dev/video0

super + shift + w
	xwininfo | grep 'Window id' | grep -Eo '0x[0-9a-fA-F]+' | xclip -selection c
	
super + grave
	emoji | xclip -selection c

super + F4
	theme reset
